[web]
name = "task-manager-frontend"
env = "node"
startCommand = "npm run preview"
buildCommand = "npm run build"
envVars = [
  { key = "VITE_API_URL", fromRenderSecrets = true }
]
instanceType = "shared-cpu"
autoDeploy = true
