[web]
name = "task-manager-api"
env = "node"
startCommand = "cd server && node index.js"
buildCommand = "cd server && npm install"
envVars = [
  { key = "MONGODB_URI", value = "mongodb+srv://jasikudakwashe42:XSsVs9VzDlBqkzzT@cluster0.rksmdnu.mongodb.net/taskmanager?retryWrites=true&w=majority" },
  { key = "PORT", value = "8800" },
  { key = "JWT_SECRET", value = "kjewhuhewhugheygy" }
]
nodeVersion = "18"
instanceType = "shared-cpu"
autoDeploy = true
workingDirectory = "server"

[web.build]
command = "cd server && npm install"
directory = "server"
