[web]
name = "task-manager-api"
env = "node"
startCommand = "npm start"
buildCommand = "npm install"
envVars = [
  { key = "MONGODB_URI", value = "mongodb+srv://jasikudakwashe42:XSsVs9VzDlBqkzzT@cluster0.rksmdnu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" },
  { key = "PORT", value = "8800" },
  { key = "JWT_SECRET", value = "kjewhuhewhugheygy" }
]
nodeVersion = "18"
instanceType = "shared-cpu"
autoDeploy = true
root = "/opt/render/project/server"
workingDirectory = "/opt/render/project/server"

[web.build]
command = "npm install"
directory = "/opt/render/project/server"
