[web]
name = "task-manager-api"
env = "node"
startCommand = "node index.js"
buildCommand = "npm install"
envVars = [
  { key = "MONGODB_URI", value = "mongodb+srv://jasikudakwashe42:XSsVs9VzDlBqkzzT@cluster0.rksmdnu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" },
  { key = "PORT", value = "8800" },
  { key = "JWT_SECRET", value = "kjewhuhewhugheygy" },
  { key = "MONGO_URI", value = "mongodb+srv://jasikudakwashe42:XSsVs9VzDlBqkzzT@cluster0.rksmdnu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" },
  { key = "NODE_ENV", value = "production" }
]
nodeVersion = "18"
instanceType = "shared-cpu"
autoDeploy = true
root = "server"
workingDirectory = "server"

[web.build]
command = "npm install"
directory = "server"
