version: '3'
services:
  api:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=3000
    networks:
      - task-network

  frontend:
    build: ./client
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=${API_URL}
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
