[web]
name = "task-manager-api"
env = "node"
startCommand = "npm start"
buildCommand = "npm install"
envVars = [
  { key = "MONGODB_URI", value = "mongodb+srv://your_username:your_password@your_cluster.mongodb.net/your_database" },
  { key = "PORT", value = "8800" },
  { key = "JWT_SECRET", value = "your_jwt_secret" }
]
instanceType = "shared-cpu"
autoDeploy = true
