[web]
name = "task-manager-api"
env = "node"
startCommand = "npm start"
buildCommand = "npm install"
envVars = [
  { key = "MONGODB_URI", value = "mongodb+srv://jasikudakwashe42:XSsVs9VzDlBqkzzT@cluster0.rksmdnu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" },
  { key = "PORT", value = "8800" },
  { key = "JWT_SECRET", value = "kjewhuhewhugheygy" }
]
nodeVersion = "18"
instanceType = "shared-cpu"
autoDeploy = true
<<<<<<< HEAD
root = "server"
=======
root = "."
workingDirectory = "/opt/render/project/src"
>>>>>>> 8632ebc47b29a9cc52ef3a53168c234f5066a929
